### ISSUE TITLE
open docx

### ISSUE THREAD

**Issue by yangy996** [SUPERCILEX/poi-android#1]
org.apache.poi.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
        at org.apache.poi.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
        at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178)
        at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
        at org.apache.poi.javax.xml.stream.XMLEventFactory.newInstance(XMLEventFactory.java:30)
        at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
        at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
        at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:97)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
        at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
        at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:116)
        at com.sunwayworld.document.MainActivity.wordToHtml(MainActivity.java:182)
        at com.sunwayworld.document.MainActivity.openDoc(MainActivity.java:126)
        at com.sunwayworld.document.MainActivity.access$000(MainActivity.java:41)
        at com.sunwayworld.document.MainActivity$2.run(MainActivity.java:110)
        at java.lang.Thread.run(Thread.java:764)

**Comment by SUPERCILEX** [comment]
Does adding this help?

```java
System.setProperty(
        "org.apache.poi.javax.xml.stream.XMLInputFactory",
        "com.fasterxml.aalto.stax.InputFactoryImpl"
)
System.setProperty(
        "org.apache.poi.javax.xml.stream.XMLOutputFactory",
        "com.fasterxml.aalto.stax.OutputFactoryImpl"
)
System.setProperty(
        "org.apache.poi.javax.xml.stream.XMLEventFactory",
        "com.fasterxml.aalto.stax.EventFactoryImpl"
)
```

**Comment by pilowl** [comment]
Helped a lot, thanks!
